// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjKeqLyM1cOWC81oA17CwLiF_uEHHoKw',
    appId: '1:798236251436:web:55fad3b90ff1919424c889',
    messagingSenderId: '798236251436',
    projectId: 'handspeakfirebase-1b1f7',
    authDomain: 'handspeakfirebase-1b1f7.firebaseapp.com',
    storageBucket: 'handspeakfirebase-1b1f7.firebasestorage.app',
    measurementId: 'G-MGPZ9MXYKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhNPcs7TDCSijKnP-XDVmwZqOLw8D48RM',
    appId: '1:798236251436:android:47220051ff7bc3a724c889',
    messagingSenderId: '798236251436',
    projectId: 'handspeakfirebase-1b1f7',
    storageBucket: 'handspeakfirebase-1b1f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHyRlCDqz4B5zLmAMCuV1gm3ug_V9WbiQ',
    appId: '1:798236251436:ios:e9678952405f936c24c889',
    messagingSenderId: '798236251436',
    projectId: 'handspeakfirebase-1b1f7',
    storageBucket: 'handspeakfirebase-1b1f7.firebasestorage.app',
    iosBundleId: 'com.majornuckcracker.handspeak',
  );
}
